### ISSUE TITLE
Clean up links

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#113]
Is there a greater concept behind our urls?
Currently, `A` and `B` is in our link. Do we want to dynamically use `ParticipantConfig.name` in the end?

Blocked by @feeds

**Comment by feeds** [comment]
I think it would be cool to use the name form the config. But we should probably use a url_name variable in case the actual name co taines spaces ect

**Comment by feeds** [comment]
and the greater concept... i intended everything that is non user-only specific to have the A/B binding

One inconsistency in the current implementation is that the profile page is A/B specific. That is non really neccessary since that page is not accessedby someone else

**Comment by Baschdl** [comment]
I started in https://github.com/match4everyone/match4everything/tree/name_in_url but you probably have the better overview where `A` and `B` is used
