### ISSUE TITLE
Show user email and username in profile

### ISSUE THREAD

**Issue by bjrne** [match4everyone/match4everything#119]
As a normal user of the system, I want to check what email I used in my profile information.

**Comment by Baschdl** [comment]
email = username in our system

**Comment by bjrne** [comment]
Is it though? We have both fields in our db, and for superusers, these can be different. We could theoretically offer to change the username.

Either way, if we currently do email==username, shouldn't the label also state "email/username:" ? Or do we never speak of a username on the plattform?

**Comment by bjrne** [comment]
I could not find any occurences of `username` in a public facing place in the project :+1:

**Comment by Baschdl** [comment]
Yeah, it's just the case when I create superusers with mail != username
