### ISSUE TITLE
matching_participant_required restriction of ParticipantDashboard

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#125]
@feeds What was the idea behind the `matching_participant_required` restriction here: https://github.com/match4everyone/match4everything/blob/4f4687cdfb512fda8e9f5bee6d9bb851566c27c7/backend/apps/matching/views/participant_dashboard.py#L16 
I don't see how this adds any security.

**Comment by feeds** [comment]
It doesn't, I approved the PR
