### ISSUE TITLE
m4h url is hardcoded in some metas

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#127]
match4healthcare.de is hardcoded in some meta tags in `base.html`. We want to have this dynamically (there was maybe a problem) or at least editable
https://github.com/match4everyone/match4everything/blob/e9578f184bab4720422d7e48292e5f48883ba01d/backend/templates/base.html#L34-L37

**Comment by bjrne** [comment]
Would it be possible to edit this is a somewhat foolproof way with django cms? If so, it probably depends on #116 ?

**Comment by maltezacharias** [comment]
Basically any app I have setup usually has like a BASE_URL setting, maybe in Config?

**Comment by Baschdl** [comment]
I guess that's a one-time setup which is set by the admin, so I would be fine with the `BASE_URL` option
