### ISSUE TITLE
Replace all hardcoded urls with url tags in templates

### ISSUE THREAD

**Issue by bjrne** [match4everyone/match4everything#147]

**Comment by Baschdl** [comment]
Do you find something besides facebook, twitter, youtube and github?

**Comment by bjrne** [comment]
- For example 'matching/password_change' in the participant dashboard, I am sure that I have seen more.

**Comment by Baschdl** [comment]
Ah, you're referring to the question @maltezacharias already asked in https://github.com/match4everyone/match4everything/pull/105#discussion_r452454882
