### ISSUE TITLE
Change all routes to end in slashes

### ISSUE THREAD

**Issue by bjrne** [match4everyone/match4everything#157]
After a quick research, I think the best practice is for links to have a trailing slash, and to redirect links without one to that url (which is built-in behaviour of django, like documented [here](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-APPEND_SLASH)). 

Currently, routes whose paths do __not__ end in slashes but are entered with one, result in a 404.

There is more information on the [to-slash-or-not-to-slash](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html) from Google from 2010.

Do you have any take on this @maltezacharias?

**Comment by bjrne** [comment]
[This](https://stackoverflow.com/a/42213107) answer on stackoverflow also talks about it and recommends slashes, but at the end it says:

> You can't make POST/PUT/PATCH/DELETE methods to work with rest_framework unless you explicitly define APPEND_SLASH=False in settings and trailing_slash=False for each and every router you gotta use(if you use Routers). It is like you basically gonna skip this most times and you gotta waste a hell lot of time debugging this. Django recommends append slashes and doesn't force it.

So if we use the REST api for the filtering, this would be a heads-up for #81

**Comment by maltezacharias** [comment]
For the rest framework it sounds annoying, still I'd prefer trailing slashes. Your research also points towards that.
