### ISSUE TITLE
Clarify meaning of "staff"

### ISSUE THREAD

**Issue by bjrne** [match4everyone/match4everything#22]
Currently, we have `Staff`-users and users with the built-in `is_staff`-flag set.

The `is_staff` flag determines, whether a user can log into the admin panel.

Our Staff user currently only has the boolean flag whether they can approve type a and b users. These will become obsolete with the Introduction of #12 , the permission management.

My proposal would be:
Remove the staff user once #12 is closed, and limit the creation of staff users to the admin panel, where you can easily tick the `is_staff` flag, and django even has a built-in permission for that.

**Comment by bjrne** [comment]
The path forward is to remove our custom staff user and give the `is_staff`-flag to users who need administrative privileges. This still allows to have well-designed UI pages where they can approve users for example. The authorization can be implemented with fine-grained permissions if necessary.

**Comment by feeds** [comment]
Most of the discussoin is now in #51
