### ISSUE TITLE
CMS system for use case-specific texts

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#25]
Users without programming knowledge should be able to change texts and forms

Specifics have to be discussed

**Comment by Baschdl** [comment]
django cms plugins (user-editable content) could be a solution: http://docs.django-cms.org/en/latest/how_to/placeholders.html#placeholders-outside-cms

**Comment by Baschdl** [comment]
Wagtail also supports our use case: https://docs.wagtail.io/en/latest/getting_started/integrating_into_django.html# and https://docs.wagtail.io/en/latest/advanced_topics/add_to_django_project.html

**Comment by kevihiiin** [comment]
I think there are two approaches on how to use the CMS:
a) adding CMS to our application 
b) add our application to the CMS like a plugin

This could be a guide for b) using django CMS
http://docs.django-cms.org/en/latest/introduction/03-integrating_applications.html
And why to use plugins in django cms
http://docs.django-cms.org/en/latest/topics/plugins.html#why-would-you-need-to-write-a-plugin

**Comment by kevihiiin** [comment]
Maybe available plugins are important too?

**Django CMS**
Commonly used
http://docs.django-cms.org/en/latest/topics/commonly_used_plugins.html
Marketplace
https://marketplace.django-cms.org/en/addons/

**Wagtail**
https://github.com/springload/awesome-wagtail

**Comment by Baschdl** [comment]
Everything basically boils down to the question how much a non-html & non-python user and a non-python user should be able to edit

**Comment by Baschdl** [comment]
https://pypi.org/project/django-template-editor/ would be an easy way to have an UI to change the templates

**Comment by Baschdl** [comment]
Posted a question on SO, maybe the web has a better idea: https://stackoverflow.com/questions/62487635/combining-django-templates-with-content-editable-for-non-technical-users

**Comment by Baschdl** [comment]
https://docs.djangoproject.com/en/dev/ref/contrib/flatpages/ could also be a way to achieve this

**Comment by Baschdl** [comment]
Django-cms with custom plugins and [djangocms-snippet](https://github.com/divio/djangocms-snippet) for Javascript could work but would a complete rebuild of the design in django-cms require if I understand the workflow correctly. [djangocms-spa-vue-js](https://github.com/dreipol/djangocms-spa-vue-js) for vue.js single-page application support if we want this.

**Comment by maltezacharias** [comment]
> Django-cms with custom plugins and [djangocms-snippet](https://github.com/divio/djangocms-snippet) for Javascript could work but would a complete rebuild of the design in django-cms require if I understand the workflow correctly. [djangocms-spa-vue-js](https://github.com/dreipol/djangocms-spa-vue-js) for vue.js single-page application support if we want this.

Complete as in "build a template for the site for the CMS" or complete as in "rebuild every single page layout of the app in django cms"?

**Comment by maltezacharias** [comment]
> https://docs.djangoproject.com/en/dev/ref/contrib/flatpages/ could also be a way to achieve this

I think this is a viable low-level alternative if the other approaches don't work out. It's a low effort way to keep the pages maintainable without having to redeploy on every wording change. In m4h this would've worked out relatively well.

**Comment by Baschdl** [comment]
> Complete as in "build a template for the site for the CMS" or complete as in "rebuild every single page layout of the app in django cms"?

Not sure yet what the django-cms way to do this it but we can combine normal django templates with editable content

**Comment by maltezacharias** [comment]
I'll be happy to have a look together when you find the time :) I'm intrigued
