### ISSUE TITLE
Create a filterable list overview for the participants over each other

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#30]
Depends on #37 
What technique do we want to use here?

### A)
- just plain old django filtering as before, with a page reload when the filter is updated (note that github does this for issue filtering and it is hardly noticable), but with a custom filter design.

### B)
- a frontend that calls
-  our [rest api](https://www.django-rest-framework.org/api-guide/filtering/) that loads the appropriate participants on demand without necessitating a complete page reload, which seems to be quite easy
- we should also provide an endpoint to the frontend that gives back all the filtering options, so this also is configurable, but here we need to discuss the format

## Other resources
- [js table generator for filtering that is kinda cool :)](https://mdbootstrap.com/docs/jquery/tables/generator/)
- [table design suggestions](https://semantic-ui.com/collections/table.html)

### Open questions
- could we implement the hierachical enabling of filters in this way, like we had for m4h? (only enable age filter for students if they are required?)

**Comment by feeds** [comment]
@maltezacharias do you have some (even little) input on this? :)

**Comment by feeds** [comment]
For now, I will just play around with the rest api, the frontend can follow

**Comment by maltezacharias** [comment]
I strongly favor B obviously. I think we should write javascript components for every content type of field. E.g. in our filters so far we had Yes/No/Don't Care, the between A and B selector, a simple lower than or higher than selector. (And maybe more?) We should write a Vue.js UI component for these fields. These should handle translating the filter values to a format that Django can use.

Ideally the javascript would create an output that would need as little translation as possible in Django. I don't remember how you built the filters, but I remember that the names had meanings and I think it should not be a huge deal to provide this from the Javascript frontend. 

Another possibility I skimmed was using a dedicated query language lilke GraphQL if there are good django implementations for that. I think this would be a very good solution but I think it would be very costly as nobody from our teams knows GraphQL AFAIK.

We would also need an endpoint that exposes our model information (which fields exist, which UI component should be used to build a filter).

For clarification: in Vue a component can be a complete Single page app or just an input field that is rendered differently. I think we have <10 different kinds of filter UI elements. We should start with a complex one like the "Educational level between X and Y" and a simple one like "Contains text" build a javascript filter that uses both those components for a couple of fields and create a suitable filter input for the django side from that. 

The filter output could be either a plain HTTP request with parameters or a structured json document. I think the latter would be the better approach but from the JS POV it doesn't make much difference.

**Comment by Baschdl** [comment]
@maltezacharias @feeds already implemented a first draft of an REST API in https://github.com/match4everyone/match4everything/pull/40/files which returns a JSON if I understand it correctly.

I worked a bit with GraphQL and it's not too hard. Creating the API also doesn't seem to be too hard: https://github.com/graphql-python/graphene-django

**Comment by feeds** [comment]
@Baschdl would these two be the two layers you would offer? (normal and power user)

**Comment by Baschdl** [comment]
Discussed with Freya: A user should have a list of all their filters where they can duplicate existing ones (and change them afterwards) and create new ones. The user should be able to select one, a set or all filters and view their current result (`or` logic, distinct users). Emails are sent based on a distinct `or` over all filters. @maltezacharias Fine for you?

Bonus feature: Possibility to deactivate instead of deleting filters

**Comment by maltezacharias** [comment]
Yes, provided saving filters is optional and not required. I think to create an UI for this is probably one of the hardest tasks though. Question is @Baschdl should we head towards GraphQL or invent our own wheel?

**Comment by maltezacharias** [comment]
@feeds and I decided for now to stick to the REST API as she has already put considerable effort towards that way. 
@kevihiiin  and I have created #81 to start development on this
