### ISSUE TITLE
Create a persistent filter that can be applied to a participant set

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#37]
We want to be able to save a filter over the information of a participant, so we can follow up on this at a later point in time (e.g. if participants were added post-filtercreation that match the filter) and the participant can save the search in their dashboard.

This includes

- [ ] creating a custom filter for the location and time info
- [ ] creating a filter that is generated from the participant info (it might be configurable, but it should not require a config, maybe as a later issue and for now use defaults). This could mean that a text property could allow open text search, bool fields have yes/no/none, choices can be multiselected and ordered choices can be range selected etc. Some of that functionality could be reused from `django-filter`. 

#### Open Question
Do we allow more intricate logic to compose the filters (and, or...)? Facebooks search graph was an experiment that allowed this but I guess most of the population never used the features that the developers created.... ;)

**Comment by Baschdl** [comment]
"more intricate logic" would be cool but we would need to design it in a way that it can be understood easily. An idea could be to have it very low-key on the UI, only "power user" use it and the rest doesn't really notice it. How to implement it without building an interface for SQL is another question.
