### ISSUE TITLE
Add a random logo

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#4]
In general, the favicon is still from m4h, the random current logo is shitty

## Todo
- create a random logo
- create all favicon and logo svg's and pngs

## Resources
- `backend/static/img/favicon` and `backend/static/img/logo.svg`

**Comment by bjrne** [comment]
Will do!

**Comment by bjrne** [comment]
For future reference:
A website that checks the current configuration and hints for missing parts:
https://realfavicongenerator.net/favicon_checker?protocol=https&site=match4healthcare.de
