### ISSUE TITLE
[Discussion] One:One matching

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#45]
I noticed that there are several modi of matching, e.g. people just want to find each other (1:1, maybe corona school), institution wants to find many people (1:n, m4h) or an institution wants to find people working at many institutions (n:n). 

The direct impact of this decision is not in the software design but rather in the UX where and how people specify their "filter" preferences. 
- directly with their own profile information (I am ... and I need ...)
- on a form that can be used and followed up again and again (I am ... . (logged in>) I need ... and I need ...)

Many platforms mix up these two "I am" and "I need" things in one form. Since the extent of this mixture varies, it is difficult to reproduce other platforms exactly.

**Comment by Baschdl** [comment]
m4h also had m:n as some people wanted to volunteer at different locations and possibly also do multiple jobs part time but we didn't design it in this way. So A can possibly search for n Bs, and B can search for m As and A and B can have multiple locations.

**Comment by feeds** [comment]
Although we did not support the several locations in m4h ever

**Comment by Baschdl** [comment]
@maltezacharias Should m4e support this?

**Comment by maltezacharias** [comment]
Should support multiple loc's i.e. m:n? Yes

Should mix "I am" and "I need"? No, we should keep these apart for the moment as I believe that's more easily achievable. We should make searches saveable but I don't think we should make it possible to enter what you're looking for on your profile. Something comparable is easily achievable through configuration I think, like in m4h where you had some fields describing what you would like to work on, which to me seems similar to what you are describing

**Comment by feeds** [comment]
I agree @maltezacharias.

Do we want to support the use case of one hospital manager setting up different local branches?
i.e. (I am ... where I need ... AND I am ... where I need ... and I need ...)

I would suggest we do not offer this, but what do you think? It would introduce a whole new level of complexity in the UI.
In this case the hospital manager would just have a common description but could set up several addresses.

**Comment by maltezacharias** [comment]
I am sure we should offer it, but if we truly offer it we should also make the distinction between geodependent attributes and basic attributes that are the same for every location.

I agree on the complexity, I think we should do this as a second step and first focus on getting the UI done and working without multiple locations. It will probably be easier to discuss the best approach for it then. We should keep it in mind and try not to make design decisions that will obviously hurt this goal in the long run. It might be a good idea to add a location model now, but I think that is a question for you whether it will be easier to do that now rather than later

**Comment by maltezacharias** [comment]
add a location model = removing the location (e.g. zip) from the participant and create a new model that is linked to the participant and contains the location. On a sidenote we could add the lat lon there as well and let PostgreSQL handle the distance calculation, but that's another issue and debate.

**Comment by feeds** [comment]
I think it is quite easy to do now, since we would only have to reattach it to another model (i.e. the participant himself) if we changed our mind (right now it is connected to a participant info itself).

**Comment by feeds** [comment]
> add a location model = removing the location (e.g. zip) from the participant 

this is actually already the case

**Comment by bjrne** [comment]
I would reserve this as a stretch goal and get the rest of the features working before the end of July, then see if there is enough time left :)
