### ISSUE TITLE
Link the participant view in the approvals

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#55]
Approvers should be able to quickly get an overview over the participant, incuding "private" info like phone number to decide on the approval

**Comment by Baschdl** [comment]
I would say the `ParticipantInfoViewView` would be sufficient for this or would you want to show something else?
If we wanna use `ParticipantInfoViewView`, we just have to configure the permissions to require `matching_participant_required` or a staff user
![image](https://user-images.githubusercontent.com/3034832/87075859-44ab2e80-c221-11ea-8835-2ec43ac63e7a.png)

**Comment by maltezacharias** [comment]
> quickly get an overview of the participiant
I think we should employ JS to open this in a modal window. I tried the validation in m4e and I think the UX would be a lot better if you didn't need to navigate to another page everytime to check one participant. With our ~150 participants that wasn't a big issue but for other scenarios it might well be.

Best would probably be a JS hover effect that would open tooltip like window showing the Participants details, alternatively a modal window

**Comment by bjrne** [comment]
I like the idea. However, since we can't really imagine the complexity of users of our system, it would be difficult to show the relevant attributes for approving given that all of them are configurable. 

Maybe a combination of both would be good? A JS hover over the name for one or two attributes and a "more info" button for the full thing on a new page?

**Comment by feeds** [comment]
I bjarnes idea, but I would implement the full overview first

**Comment by maltezacharias** [comment]
> I like the idea. However, since we can't really imagine the complexity of users of our system, it would be difficult to show the relevant attributes for approving given that all of them are configurable.

Could just tag them in the configuration?

**Comment by bjrne** [comment]
Probably. But let's add that as a stretch goal :sweat_smile: 
Since it also adds complexity for the user at setup time, where they might not have any clue what that option is. Sure, you can edit/update the configuration later, but this sounds like a bit of work to make the UX nice.

**Comment by feeds** [comment]
@bjrne @maltezacharias [Currently](https://github.com/match4everyone/match4everything/blob/f62dcead1de94e10700e85e81190f3b1f88d6ba1/backend/apps/matching/models/participant_info.py#L89) you can actually already tag them in the configuration. You can set a Property to 'private' (GroupProperties propagate this setting to their children, so they are private as well). The model in 'participant-info.py' then implements the method 'private_fields'  to return a list of fields that are considered private (the ones that admins can view only plus data-base stuff like the uuid, that is already included in 'excluded_fields'.

**Comment by feeds** [comment]
in the config it is used like [this](https://github.com/match4everyone/match4everything/blob/f62dcead1de94e10700e85e81190f3b1f88d6ba1/backend/match4everyone/configuration/A.py#L20)

and the participant view actually already uses this [method](https://github.com/match4everyone/match4everything/blob/f62dcead1de94e10700e85e81190f3b1f88d6ba1/backend/apps/matching/forms/participant_view_info.py#L12)

if you want to have an admin view, you would only have to replace the private_fields in [this](https://github.com/match4everyone/match4everything/blob/f62dcead1de94e10700e85e81190f3b1f88d6ba1/backend/apps/matching/forms/participant_view_info.py#L12) line with excluded_fields
