### ISSUE TITLE
Prevent User creation during login

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#6]
In general,  we want to prevent users from creating another account when they are logged in.
How do we prevent this?

Using the Permissions from django.auth?

**Comment by kevihiiin** [comment]
Sounds like a good idea, maybe we can write a decorator similar to the `login_required` one

https://github.com/django/django/blob/8dabdd2cc559a66b519e2a88b64575d304b96ebe/django/contrib/auth/decorators.py#L38

- - - 
Here is a way to implement it as a middleware:
https://stackoverflow.com/a/2255206/9356180

Maybe we can use more middlewares?
https://docs.djangoproject.com/en/3.0/topics/http/middleware/
