### ISSUE TITLE
Enable staff to change the max number of contact requests a person can send per day and indroduce the field at all

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#68]
We did not have this ability in m4h and this was slightly annoying for the admins

The field needs to be introduced on the abstract model class of participantA/B

@Baschdl:
Use the same functionality and design like the approval pages but to provide the possibility to increase the mail limit

**Comment by Baschdl** [comment]
Is this a piece of code which didn't make it from m4h because there we had a restriction on the number of mails? I would introduce it for A and B because a volunteer could also be a spammer. Any thoughts?

**Comment by Baschdl** [comment]
@feeds:
Maxemails was a database entry  in m4h and also used in the code. That code didnt make it because it was hospital specific.

Editing it as a staff member was never implemented in m4h, but much desired
And introducing it for both A and B was the suggestion I made in the description in the first place:wink:

**Comment by Baschdl** [comment]
> Editing it as a staff member was never implemented in m4h, but much desired

So we need the page suggested by @maltezacharias where one can search for all participants and increase the maximum if requested

**Comment by Baschdl** [comment]
@feeds:
yes
it could be integrated into the approvals
just a search field on top

**Comment by Baschdl** [comment]
[...]

**Comment by Baschdl** [comment]
What you change the approval interface? My idea was to have three different lists: 0-2 lists listing participants for approving without search, two listing participants for increasing the mails with search and one listing staff users to grant them special permissions

**Comment by Baschdl** [comment]
@feeds:
i would make the approval list seaechable as well. m4h users complained when they wanted to reverse aprovals
but i can agree that two lists are fine
one for approval and one for email limits
and then one for stafg users
so 3
[...]
so 5 if you want

**Comment by Baschdl** [comment]
[...]
So one would type something in the search field, press enter and then the page would reload with a filtered django_tables2
[...]
For everything else would probably need to add an REST endpoint for the search and abandon django_tables
[...]
As we have two tables on the approval page, we have to reissue a possibly other search and store the pagination
