### ISSUE TITLE
Include config for B, script for rebuilding project from configuration.

### ISSUE THREAD

**Issue by josauder** [match4everyone/match4everything#69]
- As of right now, A and B both use the class for A.
- Also, building the project right now from scratch requires moving `0002_permission_group_creation.py` to a different folder, deleting all other migrations, running `makemigrations && migrate`, and then re-adding `0002_permission_group_creation.py`.

**Comment by bjrne** [comment]
Now that we use the automatic configuration, there might be a better way to add the groups, like automatically loading a fixture? I'm not a huge fan of it since it is less verbose in code, but it could be way easier here.

**Comment by Baschdl** [comment]
Closed with #70
