### ISSUE TITLE
Handle deletion and deactivation of users

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4everything#76]
The links are in the dashboard, but do not work.

Best idea: Take what is there in m4h and copy+paste :)

**Comment by Baschdl** [comment]
I mean the methods are here
https://github.com/match4everyone/match4everything/blob/4f4687cdfb512fda8e9f5bee6d9bb851566c27c7/backend/apps/matching/views/user_deletion.py#L13

and they are also linked with the button

https://github.com/match4everyone/match4everything/blob/4f4687cdfb512fda8e9f5bee6d9bb851566c27c7/backend/apps/matching/templates/messages/deleted_user_ask.html#L49

Not sure where this fails
