### ISSUE TITLE
Mapbox vs OSM tile server

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#8]
Should we add the public OSM tile server as an option and make it the standard setting? With this, a first installation wouldn't be dependent on Mapbox

**Comment by bjrne** [comment]
How much work would be needed for this though? Is it just a leaflet setting? Also, scope of this issue would probably include to adjust the mapbox api key warning, to whoever will work on this ;)

**Comment by Baschdl** [comment]
It's basically just using another URL for the tiles
