### ISSUE TITLE
User signup results in django.db.utils.DataError

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#9]
Signing up as User A results in `django.db.utils.DataError: value too long for type character varying(3)`

**Comment by kevihiiin** [comment]
The error does only occur when using the Docker container.
I tried to run the system without Docker but with production settings (and SQLite instead of postgres) and it works.

So either docker or postgres is the issue

**Comment by Baschdl** [comment]
My best guess would be postgres from the error message

**Comment by Baschdl** [comment]
Doesn't happen anymore
