### ISSUE TITLE
Fix X-Frame-Options for django-cms

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4everything#99]
Editing a plugin on https://helping-health.from-de.com/ throws a `The loading of “https://helping-health.from-de.com/admin/cms/page/edit-plugin/1/?cms_path=/?edit” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.`-error

**Comment by kevihiiin** [comment]
It's a Django settings option and (I think) independent from the nginx settings. From Django 3.0 on it is application wide set to deny per default. 

You can exclude a specific view or set the option to something else in general. 

If you need to only embed one view I would recommend to use the decorator. If we need more just set the whole site to "same origin". 

https://docs.djangoproject.com/en/3.0/ref/clickjacking/

**Comment by Baschdl** [comment]
@kevihiiin It's already set as django-cms needs it for multiple things:

https://github.com/match4everyone/match4everything/blob/55428b9d813949a87618fccde68e888ef3428a78/backend/match4everyone/settings/common.py#L118

Maybe we set it to `DENY` with nginx?

**Comment by Baschdl** [comment]
`DENY` is set by the reverse-proxy in front of our site
